
let level1:String=
#|{
#|  "world_settings": {
#|    "gravity": [
#|      0,
#|      -9.8
#|    ],
#|    "allow_sleeping": true,
#|    "auto_clear_forces": true
#|  },
#|  "bodies": [
#|    {
#|      "id": "body_1760796354261_8xkqzmqy7",
#|      "body_def": {
#|        "type": "static",
#|        "position": [
#|          -15.899999999999999,
#|          3.649999999999997
#|        ],
#|        "angle": 0,
#|        "linear_velocity": [
#|          0,
#|          0
#|        ],
#|        "angular_velocity": 0,
#|        "linear_damping": 0,
#|        "angular_damping": 0,
#|        "allow_sleep": true,
#|        "awake": true,
#|        "fixed_rotation": false,
#|        "bullet": false,
#|        "gravity_scale": 1
#|      },
#|      "fixtures": [
#|        {
#|          "shape": {
#|            "type": "box",
#|            "params": {
#|              "width": 10,
#|              "height": 1
#|            }
#|          },
#|          "fixture_def": {
#|            "density": 1,
#|            "friction": 0.3,
#|            "restitution": 0.5,
#|            "is_sensor": false,
#|            "filter_category_bits": 1,
#|            "filter_mask_bits": 65535,
#|            "filter_group_index": 0
#|          }
#|        }
#|      ],
#|      "visual_properties": {},
#|      "user_data": {}
#|    },
#|    {
#|      "id": "body_1760796380543_r63xejldw",
#|      "body_def": {
#|        "type": "static",
#|        "position": [
#|          -5.774999999999998,
#|          8.9
#|        ],
#|        "angle": 0,
#|        "linear_velocity": [
#|          0,
#|          0
#|        ],
#|        "angular_velocity": 0,
#|        "linear_damping": 0,
#|        "angular_damping": 0,
#|        "allow_sleep": true,
#|        "awake": true,
#|        "fixed_rotation": false,
#|        "bullet": false,
#|        "gravity_scale": 1
#|      },
#|      "fixtures": [
#|        {
#|          "shape": {
#|            "type": "box",
#|            "params": {
#|              "width": 10,
#|              "height": 1
#|            }
#|          },
#|          "fixture_def": {
#|            "density": 1,
#|            "friction": 0.3,
#|            "restitution": 0.5,
#|            "is_sensor": false,
#|            "filter_category_bits": 1,
#|            "filter_mask_bits": 65535,
#|            "filter_group_index": 0
#|          }
#|        }
#|      ],
#|      "visual_properties": {},
#|      "user_data": {}
#|    },
#|    {
#|      "id": "body_1760796448787_nhjivvkra",
#|      "body_def": {
#|        "type": "static",
#|        "position": [
#|          7.85,
#|          19.275
#|        ],
#|        "angle": 0,
#|        "linear_velocity": [
#|          0,
#|          0
#|        ],
#|        "angular_velocity": 0,
#|        "linear_damping": 0,
#|        "angular_damping": 0,
#|        "allow_sleep": true,
#|        "awake": true,
#|        "fixed_rotation": false,
#|        "bullet": false,
#|        "gravity_scale": 1
#|      },
#|      "fixtures": [
#|        {
#|          "shape": {
#|            "type": "box",
#|            "params": {
#|              "width": 1,
#|              "height": 19.45
#|            }
#|          },
#|          "fixture_def": {
#|            "density": 1,
#|            "friction": 0.3,
#|            "restitution": 0.5,
#|            "is_sensor": false,
#|            "filter_category_bits": 1,
#|            "filter_mask_bits": 65535,
#|            "filter_group_index": 0
#|          }
#|        }
#|      ],
#|      "visual_properties": {},
#|      "user_data": {}
#|    },
#|    {
#|      "id": "body_1760796499813_fcoevvg6m",
#|      "body_def": {
#|        "type": "static",
#|        "position": [
#|          16.0875,
#|          10.737499999999999
#|        ],
#|        "angle": 0,
#|        "linear_velocity": [
#|          0,
#|          0
#|        ],
#|        "angular_velocity": 0,
#|        "linear_damping": 0,
#|        "angular_damping": 0,
#|        "allow_sleep": true,
#|        "awake": true,
#|        "fixed_rotation": false,
#|        "bullet": false,
#|        "gravity_scale": 1
#|      },
#|      "fixtures": [
#|        {
#|          "shape": {
#|            "type": "polygon",
#|            "params": {
#|              "vertices": [
#|                [
#|                  4.112500000000001,
#|                  4.862500000000001
#|                ],
#|                [
#|                  -5.0375,
#|                  -3.8375000000000004
#|                ],
#|                [
#|                  -4.1875,
#|                  -4.887499999999999
#|                ],
#|                [
#|                  5.112500000000001,
#|                  3.8625000000000007
#|                ]
#|              ]
#|            }
#|          },
#|          "fixture_def": {
#|            "density": 1,
#|            "friction": 0.3,
#|            "restitution": 0.5,
#|            "is_sensor": false,
#|            "filter_category_bits": 1,
#|            "filter_mask_bits": 65535,
#|            "filter_group_index": 0
#|          }
#|        }
#|      ],
#|      "visual_properties": {},
#|      "user_data": {}
#|    }
#|  ],
#|  "joints": []
#|}